# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': '북마크'},
        ),
    ]
